/*PLEASE DO NOT EDIT THIS CODE*/
/*This code was generated using the UMPLE 1.18.0.3036 modeling language!*/
package com.baidu.drapi.autosdk.sms.v3;

public interface NewCreativeService
{
  
  // ABSTRACT METHODS 

 public GetSublinkIdByAdgroupIdResponse getSublinkIdByAdgroupId(GetSublinkIdByAdgroupIdRequest GetSublinkIdByAdgroupIdRequest);
 public GetSublinkBySublinkIdResponse getSublinkBySublinkId(GetSublinkBySublinkIdRequest GetSublinkBySublinkIdRequest);
 public AddSublinkResponse addSublink(AddSublinkRequest AddSublinkRequest);
 public UpdateSublinkResponse updateSublink(UpdateSublinkRequest UpdateSublinkRequest);
 public DeleteSublinkResponse deleteSublink(DeleteSublinkRequest DeleteSublinkRequest);
 public AddMobileSublinkResponse addMobileSublink(AddMobileSublinkRequest AddMobileSublinkRequest);
 public UpdateMobileSublinkResponse updateMobileSublink(UpdateMobileSublinkRequest UpdateMobileSublinkRequest);
 public GetMobileSublinkIdByAdgroupIdResponse getMobileSublinkIdByAdgroupId(GetMobileSublinkIdByAdgroupIdRequest GetMobileSublinkIdByAdgroupIdRequest);
 public GetMobileSublinkBySublinkIdResponse getMobileSublinkBySublinkId(GetMobileSublinkBySublinkIdRequest GetMobileSublinkBySublinkIdRequest);
 public AddPhoneResponse addPhone(AddPhoneRequest AddPhoneRequest);
 public UpdatePhoneResponse updatePhone(UpdatePhoneRequest UpdatePhoneRequest);
 public GetPhoneIdByAdgroupIdResponse getPhoneIdByAdgroupId(GetPhoneIdByAdgroupIdRequest GetPhoneIdByAdgroupIdRequest);
 public GetPhoneByPhoneIdResponse getPhoneByPhoneId(GetPhoneByPhoneIdRequest GetPhoneByPhoneIdRequest);
 public AddBridgeResponse addBridge(AddBridgeRequest AddBridgeRequest);
 public UpdateBridgeResponse updateBridge(UpdateBridgeRequest UpdateBridgeRequest);
 public GetBridgeIdByAdgroupIdResponse getBridgeIdByAdgroupId(GetBridgeIdByAdgroupIdRequest GetBridgeIdByAdgroupIdRequest);
 public GetBridgeByBridgeIdResponse getBridgeByBridgeId(GetBridgeByBridgeIdRequest GetBridgeByBridgeIdRequest);
}